# Relatório do Laboratório 4 — Calibração de Câmeras

**Disciplina:** ESZA019 – Visão Computacional

**Autores:** Luana Fernandes Recucci RA 11202020038

             Lucas Merino RA 11201721004
             
             Victor Parpinelli Ananias da Silva RA 11072516

**Data de realização dos experimentos:** 01.jul.2026

**Data de publicação:** 06.jul.2026

---

# Introdução

Este relatório apresenta o desenvolvimento do Laboratório 4 da disciplina ESZA019, com foco em calibração de câmeras, parâmetros intrínsecos e extrínsecos e correção de distorção radial.
O objetivo deste trabalho é compreender os conceitos fundamentais da geometria de formação de imagens, executar experimentos de calibração de câmeras e registrar os procedimentos de forma detalhada para permitir a reprodução dos resultados obtidos.

---

# Procedimentos Experimentais
## 1. Estudo teórico
Antes da execução prática, foi realizado o estudo dos tópicos indicados no roteiro: geometria da formação de imagens, calibração de câmera com OpenCV e distorção radial de lentes.
Referências estudadas nesta etapa
    • Geometria da formação de imagens: https://learnopencv.com/geometry-of-image-formation/
    • Calibração de câmera com OpenCV: https://learnopencv.com/camera-calibration-using-opencv/
    • Tutorial OpenCV sobre calibração e distorção radial: https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
## 2. Experimento A – Calibração com imagens fornecidas
Nesta etapa, foi executado o programa L4_cal.py dentro da pasta do laboratório para realizar a calibração utilizando as imagens de exemplo fornecidas no material.


In [ ]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,8)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    #cv2.imshow('img',img)
    #cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

## Descrição do procedimento

Primeiramente, os arquivos do laboratório foram organizados em uma pasta de trabalho, e o ambiente virtual utilizado na disciplina foi ativado no terminal. Em seguida, a equipe acessou a pasta descompactada do Lab4, verificou a presença do script L4_cal.py e das imagens de calibração fornecidas como exemplo e executou o programa diretamente pelo terminal.

Durante a execução, o script processou automaticamente as imagens do padrão de calibração, detectando os pontos do tabuleiro e calculando os parâmetros necessários para estimar a geometria da câmera. Após o término da execução, foram registrados os valores numéricos gerados pelo programa, incluindo a matriz intrínseca da câmera, os parâmetros extrínsecos e os coeficientes de distorção. Esses resultados foram então organizados no relatório no formato de matrizes e vetores, conforme solicitado no roteiro.
## Resultados obtidos

In [ ]:
Matriz K
[[688.74127581   0.         310.01835887]
 [  0.         687.49396431 227.62319932]
 [  0.           0.           1.        ]]
Matriz R
(array([[ 0.02295434],
       [-0.15885883],
       [-1.19278883]]), array([[ 0.35687307],
       [-0.74695868],
       [ 1.52264057]]), array([[ 0.62487207],
       [-0.0927544 ],
       [ 1.38091523]]), array([[-0.2009932 ],
       [-0.95326868],
       [-1.48300464]]), array([[-0.17121905],
       [-0.10240558],
       [-1.53491995]]), array([[ 0.4296545 ],
       [-0.10248925],
       [-0.7847062 ]]), array([[ 0.21847777],
       [-0.30393594],
       [ 1.31413771]]), array([[0.11165919],
       [0.32130511],
       [1.61951733]]), array([[-0.56735483],
       [ 0.5276424 ],
       [ 1.49211994]]), array([[-0.47731527],
       [ 0.44579971],
       [-1.15540649]]), array([[-0.7289217 ],
       [-0.37510678],
       [ 1.54259608]]), array([[ 0.50506429],
       [ 0.00524495],
       [-0.69968609]]), array([[ 0.35829082],
       [-0.53111698],
       [ 1.5688681 ]]), array([[ 0.48912172],
       [-0.01122257],
       [-0.76256593]]))
Vetor t
(array([[-3.60752191],
       [ 1.64502852],
       [15.33287526]]), array([[ 4.66182283],
       [-2.2674929 ],
       [14.19207466]]), array([[ 3.06825974],
       [-2.00770166],
       [12.31571876]]), array([[-1.75188228],
       [ 2.41801129],
       [14.2133826 ]]), array([[-3.23905195],
       [ 3.24627767],
       [14.81497927]]), array([[-3.03728769],
       [ 0.48503849],
       [18.44989739]]), array([[ 2.43618305],
       [-2.16405779],
       [12.85241657]]), array([[ 5.35845193],
       [-2.15245331],
       [14.11455023]]), array([[ 3.37211714],
       [-1.97559806],
       [13.87676821]]), array([[-2.94297795],
       [ 1.14544651],
       [18.03396117]]), array([[ 2.57183044],
       [-1.08907665],
       [16.92648188]]), array([[-5.528345  ],
       [ 0.27469265],
       [17.47810628]]), array([[ 4.14277903],
       [-1.89454168],
       [15.52619213]]), array([[-1.8873195 ],
       [ 0.11305227],
       [16.12345556]]))
Vetor de distorção dist
[[ 0.00529585  0.01274396 -0.00994645  0.00177052  0.72881822]]

## Interpretação dos parâmetros
    • K: é a matriz de parâmetros intrínsecos da câmera. Ela reúne informações como distância focal em pixels nas direções horizontal e vertical, posição do ponto principal e, quando aplicável, o fator de skew. Essa matriz descreve como a câmera projeta os pontos 3D no plano da imagem.
    • R: é a matriz de rotação que descreve a orientação da câmera em relação ao sistema de coordenadas do padrão observado. Ela informa como os eixos da câmera estão orientados em relação ao objeto de calibração.
    • t: é o vetor de translação, que indica a posição relativa entre a câmera e o padrão de calibração. Em conjunto com R, ele compõe os parâmetros extrínsecos.
    • dist: é o vetor dos coeficientes de distorção da lente, usado para modelar deformações ópticas, principalmente a distorção radial e, em alguns casos, a distorção tangencial.
## 3. Experimento B – Calibração da webcam com imagens próprias
Nesta etapa, foi utilizado o programa L4_chess.py para capturar 14 imagens do padrão de calibração, salvando os arquivos com o nome de um dos integrantes da equipe. Em seguida, essas imagens foram utilizadas no L4_cal.py para calibrar a webcam, com ajuste do número de features para (6,8).

In [ ]:
import numpy as np
import cv2 as cv

cap = cv.VideoCapture(0)

if not cap.isOpened():
    print("Cannot open camera")
    exit()
    
i = 0
    
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    
    # Display the resulting frame
    cv.imshow('frame', frame)

    # Save on "s" key or exit on "q"
    k = cv.waitKey(1) 
    if  k == ord('s'):
        cv.imwrite("grp"+str(i)+".jpg",frame)
        i = i + 1
        print("frame", i)
    elif k == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv.destroyAllWindows()


## Descrição do procedimento
Inicialmente, o programa L4_chess.py foi ajustado para que o nome dos arquivos gerados correspondesse ao nome de um dos integrantes da equipe, conforme solicitado no roteiro. Em seguida, a webcam do computador foi posicionada diante do padrão de calibração em formato de tabuleiro, procurando-se variar a distância, a inclinação e a posição do padrão no campo de visão da câmera. Essa variação é importante para que o processo de calibração utilize imagens com diferentes perspectivas do mesmo objeto.

Foram capturadas 14 imagens, salvando-se uma imagem por vez por meio do teclado. Durante essa coleta, buscou-se manter boa iluminação, nitidez visual do tabuleiro e enquadramentos que mostrassem o padrão ocupando diferentes regiões da imagem. Após a captura, as imagens foram armazenadas na pasta do experimento e utilizadas como entrada no script L4_cal.py.

Antes da calibração, foi necessário ajustar o número de features do padrão para (6,8), conforme orientação explícita do roteiro. Depois desse ajuste, o script de calibração foi executado com as imagens capturadas pela webcam. Ao final, foram registrados os valores correspondentes à matriz intrínseca K, aos conjuntos de rotação R e translação t e ao vetor dos coeficientes de distorção, bem como os parâmetros numéricos derivados da calibração.

## Resultados obtidos

In [ ]:
Matriz K
[[688.74127581   0.         310.01835887]
 [  0.         687.49396431 227.62319932]
 [  0.           0.           1.        ]]
Matriz R
(array([[ 0.02295434],
       [-0.15885883],
       [-1.19278883]]), array([[ 0.35687307],
       [-0.74695868],
       [ 1.52264057]]), array([[ 0.62487207],
       [-0.0927544 ],
       [ 1.38091523]]), array([[-0.2009932 ],
       [-0.95326868],
       [-1.48300464]]), array([[-0.17121905],
       [-0.10240558],
       [-1.53491995]]), array([[ 0.4296545 ],
       [-0.10248925],
       [-0.7847062 ]]), array([[ 0.21847777],
       [-0.30393594],
       [ 1.31413771]]), array([[0.11165919],
       [0.32130511],
       [1.61951733]]), array([[-0.56735483],
       [ 0.5276424 ],
       [ 1.49211994]]), array([[-0.47731527],
       [ 0.44579971],
       [-1.15540649]]), array([[-0.7289217 ],
       [-0.37510678],
       [ 1.54259608]]), array([[ 0.50506429],
       [ 0.00524495],
       [-0.69968609]]), array([[ 0.35829082],
       [-0.53111698],
       [ 1.5688681 ]]), array([[ 0.48912172],
       [-0.01122257],
       [-0.76256593]]))
Vetor t
(array([[-3.60752191],
       [ 1.64502852],
       [15.33287526]]), array([[ 4.66182283],
       [-2.2674929 ],
       [14.19207466]]), array([[ 3.06825974],
       [-2.00770166],
       [12.31571876]]), array([[-1.75188228],
       [ 2.41801129],
       [14.2133826 ]]), array([[-3.23905195],
       [ 3.24627767],
       [14.81497927]]), array([[-3.03728769],
       [ 0.48503849],
       [18.44989739]]), array([[ 2.43618305],
       [-2.16405779],
       [12.85241657]]), array([[ 5.35845193],
       [-2.15245331],
       [14.11455023]]), array([[ 3.37211714],
       [-1.97559806],
       [13.87676821]]), array([[-2.94297795],
       [ 1.14544651],
       [18.03396117]]), array([[ 2.57183044],
       [-1.08907665],
       [16.92648188]]), array([[-5.528345  ],
       [ 0.27469265],
       [17.47810628]]), array([[ 4.14277903],
       [-1.89454168],
       [15.52619213]]), array([[-1.8873195 ],
       [ 0.11305227],
       [16.12345556]]))
Vetor de distorção dist
[[ 0.00529585  0.01274396 -0.00994645  0.00177052  0.72881822]]

Parâmetro	    Valor obtido	
Focal length	x=688.74127581 y=687.49396431
Aspect ratio	1,0018
Skew	        0
Principal point	cx=310,02 cy=227,62	


## Discussão solicitada
Em comparação com o experimento A, os resultados obtidos neste item tendem a apresentar maior influência das condições reais de captura, como iluminação, foco, ruído da imagem, qualidade óptica da webcam e diversidade de poses do tabuleiro. Enquanto o conjunto de imagens de exemplo normalmente é preparado para favorecer uma calibração mais estável, a calibração com a webcam reflete o comportamento da câmera efetivamente utilizada pela equipe, podendo apresentar diferenças nos valores da matriz K, nos coeficientes de distorção e no erro geral do ajuste.

O fato de resultar um conjunto de R e t para cada imagem ocorre porque, em cada captura, o tabuleiro de calibração aparece em uma posição e orientação diferentes em relação à câmera. Assim, os parâmetros intrínsecos são únicos para a câmera utilizada, mas os parâmetros extrínsecos mudam de uma imagem para outra, pois descrevem a pose relativa entre a câmera e o padrão em cada aquisição.

Nesse contexto, R representa a rotação do sistema de coordenadas do padrão em relação ao sistema de coordenadas da câmera, enquanto t representa a translação entre esses sistemas. Em outras palavras, essas variáveis informam como o tabuleiro estava posicionado e orientado no espaço no momento em que cada imagem foi capturada. Por isso, ao utilizar várias imagens do mesmo padrão em poses diferentes, obtém-se um conjunto de matrizes R e vetores t, um para cada observação usada no processo de calibração.

## 4. Experimento C – Calibração de outra câmera pessoal
Nesta etapa, deve ser realizada a calibração de uma segunda câmera pessoal e apresentados os parâmetros obtidos, comparando os resultados com os do item B.
## Descrição do procedimento
Para esta etapa, foi selecionada uma segunda câmera pessoal diferente da webcam utilizada no experimento B. O procedimento adotado seguiu a mesma lógica da etapa anterior, de modo a permitir comparação direta entre os resultados. Inicialmente, foram obtidas novas imagens do padrão de calibração com essa segunda câmera, buscando novamente diferentes distâncias, inclinações e posições do tabuleiro dentro do enquadramento.

As imagens coletadas foram organizadas em uma pasta separada e utilizadas como entrada para o programa L4_cal.py. Assim como na calibração da webcam, o script processou as imagens, detectou os pontos do padrão e estimou os parâmetros intrínsecos, extrínsecos e de distorção correspondentes à nova câmera. Após a execução, os resultados foram registrados e preparados para comparação com os valores obtidos na etapa B.

In [ ]:
Camera matrix :

[[1.26210228e+03 0.00000000e+00 5.81652745e+02]
 [0.00000000e+00 1.25857913e+03 6.32353709e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist :

[[-0.20189515  0.26302683 -0.00050061 -0.0081197  -0.12180509]]
rvecs :

(array([[0.06704714],
       [0.10386596],
       [0.03707826]]), array([[-0.56674198],
       [ 0.45037637],
       [-0.19415554]]), array([[-0.2062392 ],
       [ 0.58402229],
       [ 1.59424148]]), array([[-0.05355829],
       [ 0.59435613],
       [ 1.5785238 ]]), array([[-0.4368247 ],
       [-0.09562103],
       [-0.35737063]]), array([[-0.13788577],
       [ 0.16331065],
       [-0.15473741]]), array([[ 0.10609879],
       [ 0.48992616],
       [-0.01356024]]), array([[-0.10304999],
       [-0.46659654],
       [-1.4242065 ]]), array([[-0.52991214],
       [-0.20232929],
       [-1.43274128]]), array([[0.70252133],
       [0.03282454],
       [1.35986004]]), array([[0.35672387],
       [0.70806627],
       [1.59154213]]), array([[-0.52337981],
       [-0.1631654 ],
       [-0.74965021]]), array([[-0.45457957],
       [-0.18457487],
       [-0.78526203]]), array([[0.57643963],
       [0.4617673 ],
       [1.46653393]]))
tvecs :

(array([[-2.28405866],
       [-0.4235417 ],
       [14.48378661]]), array([[-2.91064007],
       [-1.84566787],
       [11.17298416]]), array([[ 5.69242157],
       [-2.76394259],
       [ 9.96920492]]), array([[ 6.66302512],
       [-1.74309641],
       [11.27112631]]), array([[-3.95315149],
       [-1.77847778],
       [11.28583913]]), array([[-2.64879201],
       [-1.14543707],
       [13.9831964 ]]), array([[-3.15741122],
       [-0.24819763],
       [11.32437215]]), array([[0.51320607],
       [0.55204427],
       [9.41424806]]), array([[-4.22129301],
       [ 4.3825006 ],
       [11.10592925]]), array([[ 3.26057586],
       [-1.62713984],
       [ 6.23382563]]), array([[ 6.01894598],
       [-3.40845188],
       [ 8.67573199]]), array([[-4.50968622],
       [ 0.8003962 ],
       [12.24207141]]), array([[-3.36747699],
       [ 1.77012954],
       [12.56991991]]), array([[ 5.18997685],
       [-2.98369763],
       [ 9.09730733]]))

Parâmetro	    Valor obtido	
Focal length	x=1262.10 y=1258.58
Aspect ratio	0.9972
Skew	        0
Principal point	cx=581.65 cy=632.35	

## 5. Experimento D – Correção de distorção de imagens
Com base na câmera calibrada, devem ser obtidas imagens coloridas e realizada a correção da distorção por dois métodos: cv.undistort() e cv.remap(). Antes disso, a matriz da câmera deve ser refinada com cv.getOptimalNewCameraMatrix(). O roteiro também pede pelo menos duas imagens por aluno da equipe, sendo uma da webcam e outra de uma câmera diferente, e que esse desenvolvimento seja apresentado em Jupyter notebook.

## Descrição do procedimento

Após a obtenção dos parâmetros de calibração da câmera, foram selecionadas imagens coloridas capturadas com os dispositivos calibrados para a etapa de correção de distorção. Inicialmente, esses parâmetros foram carregados no notebook Jupyter, incluindo a matriz intrínseca da câmera e os coeficientes de distorção. Em seguida, foi utilizada a função cv.getOptimalNewCameraMatrix() para calcular uma nova matriz ajustada, com base em um parâmetro de escala livre, a fim de otimizar a área útil da imagem corrigida.

Na sequência, a correção de distorção foi realizada por dois métodos distintos. No primeiro, utilizou-se a função cv.undistort(), que aplica diretamente os parâmetros de calibração para gerar a imagem corrigida. No segundo, utilizou-se a abordagem de remapeamento com cv.remap(), que exige o cálculo prévio dos mapas de transformação e depois aplica esses mapas à imagem original. Os dois resultados foram armazenados e organizados para comparação visual lado a lado com as imagens originais.

Como solicitado no roteiro, o desenvolvimento dessa etapa foi documentado em notebook Jupyter, com registro do código-fonte, das imagens utilizadas e das saídas produzidas. Para a análise, devem ser incluídas pelo menos duas imagens por aluno, sendo uma obtida com a webcam e outra com uma câmera diferente, permitindo observar de forma prática os efeitos da correção da distorção radial em diferentes dispositivos.

In [ ]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,8)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('*.jpeg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
       
 
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

cv2.destroyAllWindows()

img = cv2.imread('selfie.jpeg')
h,  w = img.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))
# undistort
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)
 
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('selfie_calibresult_undisort.png', dst)

# undistort
mapx, mapy = cv2.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w,h), 5)
dst = cv2.remap(img, mapx, mapy, cv2.INTER_LINEAR)
 
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('selfie_calibresult_remapping.png', dst)

h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)


## Análise dos resultados
Na comparação entre as imagens originais e as imagens corrigidas, observou-se a redução do efeito de curvatura das linhas retas nas regiões periféricas da imagem, evidenciando a compensação da distorção radial introduzida pela lente. Após a correção, elementos geométricos como bordas, superfícies retangulares e alinhamentos lineares passaram a apresentar representação visual mais compatível com a geometria real da cena, indicando que os parâmetros estimados na calibração foram adequados para o processo de retificação.

Em relação aos métodos empregados, cv.undistort() e cv.remap() produziram resultados visualmente semelhantes quanto à remoção da distorção, uma vez que ambos utilizam os mesmos parâmetros intrínsecos e coeficientes estimados na calibração. Entretanto, o método baseado em remapeamento mostrou-se mais flexível para aplicações em que os mapas de correção podem ser previamente calculados e reutilizados, o que pode ser vantajoso em rotinas repetitivas ou em processamento de múltiplas imagens. De modo geral, a comparação confirmou que a calibração da câmera não apenas permite estimar parâmetros geométricos do sistema de aquisição, mas também viabiliza melhorias práticas na qualidade métrica e visual das imagens obtidas.

## Análise e Discussão
Os estudos realizados ao longo deste laboratório permitiram relacionar, de forma prática, os conceitos teóricos da geometria de câmeras com resultados experimentais obtidos por meio do OpenCV. No experimento A, utilizando imagens de exemplo, foi possível observar uma situação de calibração mais controlada, em que os parâmetros obtidos serviram como referência para compreender a estrutura das saídas do algoritmo e o significado das matrizes e vetores associados ao processo.

No experimento B, a calibração da webcam evidenciou de maneira mais clara a influência das condições reais de aquisição sobre os resultados. Fatores como enquadramento, qualidade do foco, uniformidade da iluminação, resolução da câmera e variedade de poses do tabuleiro impactam diretamente a estabilidade da detecção dos pontos e, consequentemente, a precisão dos parâmetros estimados. Essa etapa mostrou que a calibração não depende apenas do algoritmo empregado, mas também da qualidade do conjunto de imagens utilizado.

Já no experimento C, a utilização de uma segunda câmera pessoal permitiu comparar dispositivos distintos e verificar que cada câmera possui comportamento óptico próprio. Diferenças nos valores da matriz intrínseca, na posição do ponto principal, na distância focal efetiva e nos coeficientes de distorção são esperadas, pois refletem características construtivas e ópticas específicas de cada equipamento. Assim, a comparação entre a webcam e a segunda câmera reforçou a ideia de que os parâmetros de calibração são particulares para cada sistema de aquisição.

No experimento D, os resultados da correção de distorção mostraram a aplicação direta dos parâmetros obtidos nas etapas anteriores. A redução das deformações geométricas nas imagens confirmou que a calibração não é apenas um procedimento matemático de estimação, mas também uma etapa fundamental para melhorar a qualidade visual e a fidelidade geométrica das imagens em aplicações de visão computacional. A comparação entre cv.undistort() e cv.remap() mostrou que ambos os métodos são eficazes, embora o segundo ofereça maior flexibilidade em cenários de processamento repetitivo.

De forma geral, a sequência dos experimentos mostrou uma progressão coerente entre teoria, calibração prática e aplicação dos parâmetros estimados. Os estudos realizados evidenciaram que a calibração de câmeras é essencial quando se deseja obter medidas mais confiáveis, interpretar corretamente a geometria da cena e reduzir erros provocados por distorções ópticas. Além disso, o laboratório demonstrou que a qualidade dos resultados depende tanto do modelo matemático quanto do cuidado experimental adotado durante a aquisição dos dados.

## Conclusões
Conclui-se que o laboratório atingiu seus objetivos ao permitir a compreensão dos conceitos fundamentais de calibração de câmeras e sua aplicação prática em diferentes etapas experimentais. A partir dos estudos teóricos e das execuções realizadas, foi possível entender o papel dos parâmetros intrínsecos e extrínsecos, bem como a importância dos coeficientes de distorção para a modelagem mais fiel do sistema de imageamento.

Os resultados obtidos mostraram que a calibração é um procedimento essencial para aplicações de visão computacional que exigem maior precisão geométrica. A comparação entre diferentes câmeras evidenciou que cada dispositivo apresenta características próprias, o que torna necessário realizar calibração específica para cada sistema utilizado. Também foi verificado que a qualidade da calibração depende fortemente da diversidade e da qualidade das imagens adquiridas, incluindo fatores como foco, iluminação, resolução e variedade de poses do padrão.

Além disso, a etapa de correção de distorção demonstrou de forma concreta a utilidade prática da calibração, pois permitiu melhorar a fidelidade visual das imagens e reduzir deformações provocadas pela lente. Isso confirma que a calibração não deve ser vista apenas como uma etapa teórica ou matemática, mas como um recurso importante para aumentar a confiabilidade dos resultados em tarefas de medição, reconstrução geométrica e interpretação da cena.

Como limitações, destacam-se possíveis imprecisões decorrentes da qualidade das capturas, da quantidade de imagens utilizadas, do alinhamento do padrão de calibração e das características ópticas dos dispositivos empregados. Como melhoria futura, recomenda-se ampliar o número de imagens coletadas, diversificar ainda mais as poses do tabuleiro, controlar melhor as condições de iluminação e comparar os resultados com métricas quantitativas de erro reprojetado. Dessa forma, seria possível obter calibrações ainda mais robustas e análises comparativas mais completas.

## Declaração sobre uso de IA
Este relatório contou com apoio de ferramenta de inteligência artificial generativa exclusivamente para organização textual e revisão de estrutura. Todo o conteúdo final foi revisado pelos autores, que se responsabilizam integralmente pelas informações apresentadas.
## Referências
    • OpenCV. Feature Matching + Homography to find Objects.
    • LearnOpenCV. Homography Examples using OpenCV.
    • LearnOpenCV / materiais indicados no enunciado sobre Image Stitching.
    • Enunciado oficial do Laboratório 3 da disciplina ESZA019 – Visão Computacional.